# Generated by Django 4.2.5 on 2023-09-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('done_at', models.DateField()),
                ('amount', models.FloatField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('month', models.IntegerField(choices=[(1, '1 - Janvier'), (2, '2 - Février'), (3, '3 - Mars'), (4, '4 - Avril'), (5, '5 - Mai'), (6, '6 - Juin'), (7, '7 - Juillet'), (8, '8 - Août'), (9, '9 - Septembre'), (10, '10 - Octobre'), (11, '11 - Novembre'), (12, '12 - Décembre')])),
            ],
        ),
    ]
