# Generated by Django 4.2.5 on 2023-09-27 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spents', to=settings.AUTH_USER_MODEL),
        ),
    ]
