# Generated by Django 4.2.5 on 2023-09-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spent', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spent',
            name='month',
            field=models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')]),
        ),
    ]
